/*
* Configuration of module: CanIf (CanIf_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12_XEP100
*
* Module vendor:           iSoft
* Generator version:       2.0.5
*
* Generated by iSoft Shanghai Software Lab 
*           on Thu Dec 13 16:25:42 CST 2012
*/

	 




#include "CanIf.h"
#include "Can.h"
#include "PduGlobals.h"

extern void PduR_CanIfTxConfirmation(PduIdType CanTxPduId);			


#if(STD_ON == CANIF_RECEIVE_INDICATION)
extern void PduR_CanIfRxIndication(PduIdType CanRxPduId,const uint8* CanSduPtr);			
#endif


#if(STD_ON == CANIF_BUSOFF_NOTIFICATION)
extern void CanSM_ControllerBusOff(uint8 Controller);
#endif

#if(STD_ON == CANIF_DRIVER_WAKEUP_NOTIFICATION)
extern void EcuM_SetWakeupEvent(EcuM_WakeupSourceType sources);
#endif

#if(STD_ON == CANIF_WAKEUP_VALIDATION)
extern void EcuM_ValidateWakeupEvent(EcuM_WakeupSourceType sources);
#endif



extern const Can_ConfigType CanConfigSet[1] ;
extern const Can_ControllerConfigType CanController[1];
const CanIf_ControllerDriverConfigType canControllerConfig[1] =
{
	
	{
	0,
	0xffffu,
    &CanController[0],
    },
};


 const CanIf_InitControllerConfigType CanIfInitController[1] = 
{
	/* point to can controller setup of corresponding CAN driver */
	
	
	{
		&canControllerConfig[0],
	},
	
};

const CanIf_ControllerConfigType CanIfControllerConfiguration[1] = 
{
	 
	 {
	 	CANIF_WAKEUP_SUPPORT_NO_WAKEUP,
	 	CANIF_CHANNEL_0,
	 	0,
	    &CanIfInitController[0],
	  },
     
};

const CanIf_HthConfigType CanIfHthConfigData[1] =
{
	
	{
		CANIF_BASIC_CAN,
		CANIF_CHANNEL_0,
		1,	 	
	},
	
		
};



const CanIf_HrhConfigType CanIfHrhConfigData[1] =
{
	
		
	{
	    CANIF_BASIC_CAN,
		FALSE,
		CANIF_CHANNEL_0,
		0,
		
		NULL_PTR,
		
	},
		
	
};
 
const CanIf_InitHohConfigType CanIfInitHohConfig[1] = 
{
	
   {
	 &CanConfigSet[0],
	 &CanIfHrhConfigData[0],
	 &CanIfHthConfigData[0],
   },
};

/* Configuration parameters for all the underlying CAN drivers*/
const CanIf_DriverConfigType CanIfDriverConfiguration =
{
   
    /* Configuration parameters for all the underlying CAN drivers*/
	0,

	/* Reference to the Init Hoh Configuration */
	&CanIfInitHohConfig[0],
	
	
};


CanIf_TxPduConfigType CanIfTxPduConfigData[1] = 
{
	
	{
	    /* ECU wide unique, symbolic handle for transmit CAN L-PDU.*/
		CANIF_PDU_ID_PDU_CAN_TX,
		
		/* CAN Identifier of transmit CAN L-PDUs */
		0x741,
		
		/* Data length code (in bytes) of transm Driver for CAN L-PDU transmission. */
		8,
		
		/* Defines the type of each transmit CAN L-PDU */
		CANIF_PDU_TYPE_STATIC,
		
		/* Enables and disables transmit confirmation */
		#if(STD_ON ==CANIF_READTXPDU_NOTIFY_STATUS_API)
		TRUE,
        #endif
        
        /* CAN Identifier of transmit CAN L-PDUs */
		CANIF_STANDARD_CAN,
		
		/* type of the transmit confirmation call-out */
		CANIF_USER_TYPE_CAN_PDUR,
		
		/* Name of target confirmation services to target upper layers */
		&PduR_CanIfTxConfirmation,
        
        /* The parameter refers HTH Id, to which the L-PDU belongs to. */
		&CanIfHthConfigData[0],
		
		/* Reference to the "global" Pdu structure */
		GLOBAL_PDU_ID_PDU_CAN_TX,
	},
	
};



CanIf_RxPduConfigType CanIfRxPduConfigData[1] =
{ 
	
	{
	    /* CAN ID */
		0x740,
		
		/* Data length code (in bytes) of transm Driver for CAN L-PDU transmission. */
		0x8,
		
		/* ECU wide unique, symbolic handle  for receive CAN L-PDU.  */
		CANIF_PDU_ID_PDU_CAN_Rx,
		
		/* Enables and disables the Rx buffering for reading of received L-PDU data*/
		 #if(STD_ON == CANIF_READRXPDU_DATA_API)
		TRUE,
        #endif
		
		/* Enables and disables receive indication */
        #if(STD_ON == CANIF_READRXPDU_NOTIFY_STATUS_API)
		TRUE,
        #endif
        
        /* CAN Identtifier type of receive CAN L-PDUs */
		CANIF_STANDARD_CAN,
	    
	    /*  type of the receive indication call-outs */
		CANIF_USER_TYPE_CAN_PDUR,
		
		#if(STD_ON == CANIF_RECEIVE_INDICATION)
		/*indication services to target upper layers */
		&PduR_CanIfRxIndication,
        #else
		NULL_PTR,
        #endif
        
        /* The HRH to which Rx L-PDU belongs to */
		&CanIfHrhConfigData[0],
		
		/* Reference to the "global" Pdu structure */
		GLOBAL_PDU_ID_PDU_CAN_RX,
	},
	
};

CanIf_InitConfigurationType CanIfInitConfigurationData =
{
	/*  references to the configuration setup of each underlying CAN driver */
	CanIfInitController,

	/* references to the configuration setup of each underlying CAN driver */
	CanIfInitHohConfig,

	/* configuration (parameters) of each receive CAN L-PDU */
	CanIfRxPduConfigData,

	/*  configuration (parameters) of each transmit CAN L-PDU */
	CanIfTxPduConfigData,
};

#if((STD_ON == CANIF_BUSOFF_NOTIFICATION) || (STD_ON == CANIF_DRIVER_WAKEUP_NOTIFICATION) || (STD_ON == CANIF_WAKEUP_VALIDATION))
/* Callout functions with respect to the upper layers */
const CanIf_DispatchConfigType CanIfDispatchConfigData = 
{
#if(STD_ON == CANIF_BUSOFF_NOTIFICATION)
    /* Name of target BusOff notification services  */
    
    
    
	&CanSM_ControllerBusOff,
#endif

#if(STD_ON == CANIF_DRIVER_WAKEUP_NOTIFICATION)
	/*  Name of target wakeup notification services */
	&EcuM_SetWakeupEvent,
#endif

#if(STD_ON == CANIF_WAKEUP_VALIDATION)
	/* Name of target wakeup validation notif ication services */
	&EcuM_ValidateWakeupEvent
#endif
};
#endif


/*  contains the configur ation (parameters) of all addressed
CAN transceivers */
const CanIf_TransceiverDrvConfigType CanIf_TransceiverDrvConfigData = 
{
	/* Select s whether wakeup indication notif ication is supported */
	
	
	
	FALSE,

	/* Select s whether wakeup indication notif ication is supported */
	0,
};

/* includes all necessary configurati on sub-containers */
const CanIf_ConfigType CanIfConfigData =
{
	/*  contains the configuration (parameters) of all addressed CAN controllers */
	CanIfControllerConfiguration,
#if((STD_ON == CANIF_BUSOFF_NOTIFICATION) || (STD_ON == CANIF_DRIVER_WAKEUP_NOTIFICATION) || (STD_ON == CANIF_WAKEUP_VALIDATION))
	/*  Callout functions with respect to the upper layers. */
	&CanIfDispatchConfigData,
#endif

	/*Configuration parameters for all the underlying CAN drivers */
	&CanIfDriverConfiguration,
	/*  contains the init parameters of the CAN Interface */

	&CanIfInitConfigurationData,

	/*  contains the configuration (parameters) of all addressed CAN transceivers */
	&CanIf_TransceiverDrvConfigData,
};

