/*
* Configuration of module: CanIf (CanIf_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12_XEP100
*
* Module vendor:           iSoft
* Generator version:       2.0.5
*
* Generated by iSoft Shanghai Software Lab 
*           on Thu Dec 13 16:25:42 CST 2012
*/


#ifndef CANIF_CFG_H
#define CANIF_CFG_H

#ifdef	__cplusplus
extern	"C" {
#endif


#define CANIF_READRXPDU_DATA_API              STD_OFF
#define CANIF_READRXPDU_NOTIFY_STATUS_API     STD_OFF
#define CANIF_READTXPDU_NOTIFY_STATUS_API     STD_OFF
#define CANIF_SETDYNAMICTXID_API              STD_ON
#define CANIF_DRIVER_WAKEUP_NOTIFICATION      STD_OFF
#define CANIF_TRANSCEIVER_API                 STD_OFF
#define CANIF_WAKEUP_VALIDATION               STD_OFF
#define CANIF_VERSION_INFO_API                STD_OFF
#define CANIF_TRANSMIT_CONFIRMATION           STD_ON
#define CANIF_TRANSMIT_CANCELLATION           STD_ON
#define CANIF_DEV_ERROR_DETECT                STD_OFF
#define CANIF_RECEIVE_INDICATION              STD_ON
#define CANIF_BUSOFF_NOTIFICATION             STD_OFF
#define CANIF_MUL_DRIVERS                     STD_OFF
#define CANIF_PRECOMPILE_VARIANT              STD_ON

/* enable Dlc check */
#define CANIF_DLC_CHECK                       (STD_OFF)
/*disable Tx Buffer */
#define CANIF_TX_BUFFER_USED                  (STD_OFF) 

#define CANIF_NUMBER_OF_CANTXPDUIDS          (1)

#if (STD_ON == CANIF_TX_BUFFER_USED)
/* define TxBuffer number*/
#define CANIF_NUMBER_OF_TXBUFFERS             (1)
#endif

#define CANIF_NUMBER_OF_CANRXPDUIDS           (1)

#define CANIF_CONTROLLER_CNT                  (1)

#define CANIF_CONTROLLER_CONFIGURATION_CNT    (1)    

#define CANIF_NUMBER_OF_RXBUFFERS             (1)       

#define CANIF_NUMBER_HRHCONFIGDATA            (1)    


/* binary*/
#define CANIF_BINARY  0

/* index */
#define CANIF_INDEX 1

/* linear */
#define CANIF_LINEAR 2

/* table */
#define CANIF_TABLE 3


#define CANIF_SOFTWARE_FILTER_TYPE             (CANIF_BINARY)

#define CANIF_NUMBER_OF_DYNAMIC_CANTXPDUIDS    (0)

#define CANIF_PDU_ID_PDU_CAN_Rx		0
#define CANIF_PDU_ID_PDU_CAN_TX		1

#ifdef	__cplusplus
}
#endif

#endif

