/*
* Configuration of module: Can (Can_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12_XEP100
*
* Module vendor:           iSoft
* Generator version:       2.0.2
*
* Generated by iSoft Shanghai Software Lab 
*           on Thu Dec 13 16:25:42 CST 2012
*/

	

  



#ifndef CAN_CFG_H
#define CAN_CFG_H
/**@req CAN083 develop error switch*/	
#define CAN_DEV_ERROR_DETECT             STD_OFF

/**@req CAN278 @req CAN285*/
#define CAN_HW_TRANSMIT_CANCELLATION     STD_OFF
#define CAN_INSTANCE_ID                  0u


/* number of can controllers, 1~5 for XEP100 */             
#define CAN_MAXCONTROLLERCOUNT 		     1
#define CAN_MULTIPLEXED_TRANSMISSION     STD_OFF

/**@req CAN281 MAX loop counter for timeout*/
#define CAN_TIMEOUT_DURATION             0u


/* Can_GetVersion() switch*/
#define CAN_VERSION_INFO_API             STD_OFF	
#define CAN_WAKEUP_SUPPORT               STD_OFF
	
#define CAN_MAINFUNCTION_BUSOFF_PERIOD   0u
#define CAN_MAINFUNCTION_READ_PERIOD     0u
#define CAN_MAINFUNCTION_WAKEUP_PERIOD   0u
#define CAN_MAINFUNCTION_WRITE_PERIOD    0u

/**@req CAN007*/
#define CAN_POLLING 		                 (0x01u)
#define CAN_INTERRUPT 	                     (0x00u)

#define CAN_BUSOFF_PROCESSING     		  CAN_INTERRUPT
#define CAN_WAKEUP_PROCESSING        	  CAN_INTERRUPT
#define CAN_RX_PROCESSING            	  CAN_INTERRUPT 
#define CAN_TX_PROCESSING            	  CAN_INTERRUPT


/* CAN ID format*/
#define CAN_EXTENDEDID  				  STD_OFF


#define CAN_ID_NUM			            2u

#define CAN_0_FIRSTHRH                  (0x00u)
#define CAN_0_HTHOFFSET                 (0x01u)

#define CAN_1_FIRSTHRH                  (0x02u)
#define CAN_1_HTHOFFSET                 (0x03u)

#define CAN_2_FIRSTHRH                  (0x04u)
#define CAN_2_HTHOFFSET                 (0x05u)

#define CAN_3_FIRSTHRH                  (0x06u)
#define CAN_3_HTHOFFSET                 (0x07u)

#define CAN_4_FIRSTHRH                  (0x08u)
#define CAN_4_HTHOFFSET                 (0x09u)






#define CAN_MBCOUNT 			         (0x03u)

#endif

                                             
          
