/*
* Configuration of module: Can (Can_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12_XEP100
*
* Module vendor:           iSoft
* Generator version:       2.0.2
*
* Generated by iSoft Shanghai Software Lab 
*           on Thu Dec 13 16:25:42 CST 2012
*/

	
  


#include "Can.h"
#include "Can_Cfg.h"

/*mask, Rx filter,0 match,1 ignore*/
const Can_FilterMaskType CanFilterMask[CAN_MAXCONTROLLERCOUNT] =
{	 
         0xffffffffu ,
};



const Can_ControllerConfigType CanController[CAN_MAXCONTROLLERCOUNT] =
{	
	{
    	CAN_INTERRUPT,    /* busoff processing */
    	STD_ON,
   		250u,      /* baudrate, kbps*/
    	0,     /* controller ID*/
   		3u,       /* Prog seg */
    	2u,         /* Seg1*/
    	2u,        /* Seg2*/
    	8u,        /* Time Quanta*/
    	CAN_INTERRUPT, 
   		CAN_INTERRUPT,
    	CAN_INTERRUPT,
    	30000000u,
    	0xffff,
    	CanFilterMask	/* Filter mask*/
	},
};


/*CAN hardware object config*/
const Can_HardwareObjectType CanHardwareObject[CAN_ID_NUM] =
{	
		{
			CAN_BASIC,  /*CAN handle type*/
		 	CAN_STANDARD,      /*CAN id type*/
		 	0x740u,  /*CAN id value*/
		 	0x0u,  /*  CAN object id  Rx  */
		 	CAN_RECEIVE,  
		 	&CanController[0],
		 	&CanFilterMask[0]  /* same filter mask should be set for one controller*/
		},	
		{
			CAN_BASIC, 
		 	CAN_STANDARD,  
		 	0x741,  
		 	0x1u,  /*  CAN object id   Tx */
		 	CAN_TRANSMIT,  
		 	&CanController[0],
		    NULL_PTR
		},	
};



/**@req CAN343 CAN config*/
const Can_ConfigType CanConfigSet[CAN_MAXCONTROLLERCOUNT] =
{
   	{
		&CanController[0], 
		CanHardwareObject 
	},
};

